version: "3.3"
services:
  client:
    build:
      context: ./my-app/
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - socket-server
    links:
      - socket-server
  socket-server:
    build:
      context: ./socket-io-server/
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
